<?php

/**
 * @file
 * Tide Search module functionality.
 */

use Drupal\search_api\IndexInterface;

/**
 * Implements hook_search_api_index_items_alter().
 */
function tide_search_search_api_index_items_alter(IndexInterface $index, array &$items) {
  // Get any fields of type date and format it's value to align with RFC-3339.
  $index_fields = $index->getFields();
  $date_fields = [];
  foreach ($index_fields as $index_field) {
    if ($type = $index_field->getType() === 'date') {
      $date_fields[] = $index_field;
    }
  }
  foreach ($items as $item_id => $item) {
    foreach ($date_fields as $date_field) {
      $date = $item->getField($date_field->getFieldIdentifier());
      if (isset($date) && !empty($date->getValues())) {
        $value = $date->getValues();
        $date->setValues([_tide_search_get_formatted_date($value[0])]);
        $item->setField($date_field->getFieldIdentifier(), $date);
      }
    }
  }
}

/**
 * Converts timestamp to RFC-3339 format.
 *
 * @param int $ts
 *   Timestamp.
 *
 * @return string
 *   Formatted date.
 */
function _tide_search_get_formatted_date($ts) {
  $config = \Drupal::config('system.date');
  $timezone = new DateTimeZone($config->get('timezone.default'));
  $date = new \Datetime();
  $date->setTimezone($timezone);
  $date = $date->setTimestamp($ts);

  return $date->format('Y-m-d\TH:i:sP');
}
